# Engine Yard Cloud Deploy Options
#
####################################################################
#                           IMPORTANT
#            Commit this file into your git repository.
#       These options are loaded on the server during deploy.
####################################################################
#
# Valid locations:
# * REPOSITORY_ROOT/config/ey.yml.
# * REPOSITORY_ROOT/ey.yml
#
# Further information available here:
# https://support.cloud.engineyard.com/entries/20996661-customize-your-deployment-on-engine-yard-cloud
#
# For advanced usage, see the source that loads this configuration:
# https://github.com/engineyard/engineyard-serverside/blob/master/lib/engineyard-serverside/configuration.rb
#
defaults:
  migrate: false
  migration_command: rake db:migrate --trace
  precompile_assets: true
  asset_strategy: private
  precompile_unchanged_assets: true
  keep_releases: 10

####################################################################
# Environment specific options.
#
# The options you specify here will only apply to a single environment
# that exactly matches the environment name key.
#
# Environment options will override the default options above.
#
environments:

  # These options will only apply to the EXAMPLE_ENVIRONMENT environment.
  #EXAMPLE_ENVIRONMENT:
    #precompile_unchanged_assets: true

